language: rust
sudo: false
matrix:
  include:
    - rust: nightly
      sudo: true
    - rust: stable
  allow_failures:
  - rust: nightly
addons:
  apt:
    packages:
    - libssl-dev
cache: cargo

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi
before_script: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    rustup component add clippy-preview
  fi

script: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo build --release
    cargo test --release
    cargo test --release -- --ignored
    cargo clippy -- -D warnings
  else
    cargo build
    cargo tarpaulin --out Xml --skip-clean
    bash <(curl -s https://codecov.io/bash)
  fi