language: rust
sudo: required
rust:
  - stable
  - nightly
addons:
  apt:
    packages:
    - libssl-dev
cache: cargo

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi
before_script:
- rustup component add clippy-preview

script:
- cargo test --release
- cargo clippy -- -D warnings

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi